AWSTemplateFormatVersion: '2010-09-09'
Transform: 
- AWS::Serverless-2016-10-31
Description: Compose Infrastucture

Parameters:
  DomainName:
    Type: String
    Description: Domain Name
    Default: sandbox.compose.run
  Environment:
    Type: String
    Description: Environment name
    Default: sandbox

Resources:
  # Stores artifacts for SAM deployments
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub compose-${Environment}-${AWS::Region}-artifacts
      Tags:
        - Key: Name
          Value: !Sub compose-${Environment}-${AWS::Region}-artifacts
  # Provides public domain
  PublicZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub ${DomainName} zone 
      HostedZoneTags:
      - Key: Name
        Value: !Ref DomainName
  # Wildcard Certificate for Domain
  PublicCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref PublicZone
      SubjectAlternativeNames:
      - !Sub '*.${DomainName}'
      ValidationMethod: DNS
      Tags:
      - Key: Name
        Value: !Ref DomainName
  # SES Cognito Resources
  SesCognito:
    Type: AWS::Serverless::Application
    DependsOn:
      - PublicZone
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:300398300817:applications/ses-cognito-verification
        SemanticVersion: 1.0.0
      Parameters:
        Prefix: !Sub ${AWS::StackName}
        DomainName: !Ref DomainName
        FromEmail: !Sub no-reply@${DomainName}
        ForwardingEmail: justin.menga@toptal.com
